#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: set-dwm-profile.sh [--profile laptop|desktop] [--dry-run] [--force]

Detects the machine type and writes DWM_PROFILE to:
  ~/.config/environment.d/99-dwm.conf
Also updates ~/.config/dwm/host.conf to source the active profile file.

Options:
  --profile  Force profile (laptop|desktop)
  --dry-run  Show changes without writing
  --force    Overwrite existing files
  -h, --help Show this help
USAGE
}

profile=""
dry_run=0
force=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      profile="${2:-}"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

detect_profile() {
  local chassis=""
  if command -v hostnamectl >/dev/null 2>&1; then
    chassis="$(hostnamectl chassis 2>/dev/null || true)"
    case "$chassis" in
      laptop|desktop)
        echo "$chassis"
        return 0
        ;;
    esac
  fi

  if compgen -G "/sys/class/power_supply/BAT*" >/dev/null; then
    echo "laptop"
  else
    echo "desktop"
  fi
}

if [[ -z "$profile" ]]; then
  profile="$(detect_profile)"
fi

if [[ "$profile" != "laptop" && "$profile" != "desktop" ]]; then
  echo "Invalid profile: $profile" >&2
  exit 1
fi

env_dir="$HOME/.config/environment.d"
env_file="$env_dir/99-dwm.conf"
profile_line="DWM_PROFILE=$profile"
if [[ -n "${DWM_REPO_ROOT:-}" && -d "${DWM_REPO_ROOT}/scripts" ]]; then
  repo_root="$DWM_REPO_ROOT"
elif [[ -f "$HOME/.config/dwm/repo_root" ]]; then
  repo_root="$(sed -n '1p' "$HOME/.config/dwm/repo_root")"
else
  script_path="${BASH_SOURCE[0]}"
  if command -v readlink >/dev/null 2>&1; then
    resolved="$(readlink -f -- "$script_path" 2>/dev/null || true)"
    [[ -n "$resolved" ]] && script_path="$resolved"
  fi
  repo_root="$(cd -- "$(dirname -- "$script_path")/.." && pwd)"
fi
profile_file="$repo_root/profiles/$profile.conf"
dwm_conf_dir="$HOME/.config/dwm"
host_conf="$dwm_conf_dir/host.conf"

if [[ ! -f "$profile_file" ]]; then
  echo "Missing profile file: $profile_file" >&2
  exit 1
fi

if [[ $dry_run -eq 1 ]]; then
  echo "Would write: $env_file"
  echo "$profile_line"
  echo "XDG_SESSION_TYPE=x11"
  echo "GDK_BACKEND=x11"
  echo "QT_QPA_PLATFORM=xcb"
  echo "Would write: $host_conf"
  echo "source \"$profile_file\""
  exit 0
fi

mkdir -p "$env_dir" "$dwm_conf_dir"

if [[ -f "$env_file" && $force -ne 1 ]]; then
  if grep -qxF "$profile_line" "$env_file"; then
    echo "DWM_PROFILE already set to '$profile' in $env_file"
  else
    echo "Refusing to overwrite $env_file without --force" >&2
    exit 1
  fi
else
  cat > "$env_file" <<ENV
$profile_line
XDG_SESSION_TYPE=x11
GDK_BACKEND=x11
QT_QPA_PLATFORM=xcb
ENV
  echo "Wrote $env_file"
fi

if [[ -f "$host_conf" && $force -ne 1 ]]; then
  if grep -qxF "source \"$profile_file\"" "$host_conf"; then
    echo "Profile host config already points to $profile_file"
    exit 0
  fi
  echo "Refusing to overwrite $host_conf without --force" >&2
  exit 1
fi

cat > "$host_conf" <<HOST
# Generated by set-dwm-profile.sh
source "$profile_file"
HOST

echo "Wrote $host_conf"
